### ISSUE TITLE
[ComputerVision] Error 500 when using Image Analysis Language different than default 'en'

### ISSUE THREAD

**Issue by nrobert** [PeterOrneholm/cognitive-workbench#2]
### Reproduction steps:

- Set 'Image Analysis Language' to 'es' or 'jp' for example
- Provide a valid image URL
- Launch analysis

### Expected behavior:
Result display for image

### Behavior:
Error 500

### Additional notes:
Valid supported languages are listed [here](https://westeurope.dev.cognitive.microsoft.com/docs/services/5cd27ec07268f6c679a3e641/operations/56f91f2e778daf14a499f21b) in the documentation: 'en', 'es', 'ja', 'pt', 'zh'

**Comment by nrobert** [comment]
I think I figured why this error is happening: the Analyze service is compatible with several languages, but not all "visualFeatures" (see [doc](https://westeurope.dev.cognitive.microsoft.com/docs/services/5cd27ec07268f6c679a3e641/operations/56f91f2e778daf14a499f21b)): 

- The Brands argument is only available in English.
- The Objects argument is only available in English.

As all VisualFeatures are activated in the code, it results in a 400 Bad Request on Computer Vision API call with the following content:

```
{
  "code": "NotSupportedLanguage",
  "requestId": "...",
  "message": "The input language is not supported."
}
```

@PeterOrneholm , I think about 2 options to fix it, which solution do you prefer:

1. Allow 'en' only and get all results
2. Allow all languages, and remove unsupported visual features on the fly in that case

**Comment by PeterOrneholm** [comment]
> I think I figured why this error is happening: the Analyze service is compatible with several languages, but not all "visualFeatures" (see [doc](https://westeurope.dev.cognitive.microsoft.com/docs/services/5cd27ec07268f6c679a3e641/operations/56f91f2e778daf14a499f21b)):

Thanks for finding this! I'd suggest we go with solution 2. Would you mind implement this and send a PR?

**Comment by nrobert** [comment]
Ok, I already prepared it. Just need to finalize PR #1  and then I will merge last modifications and push this one

**Comment by PeterOrneholm** [comment]
Cool. Speaking of these fields, can you remove the reuired attribute on them (languages) in HTML? Would like them to be optional as the SDK has them optional.

**Comment by nrobert** [comment]
It's "optional" in the SDK because it points to "en" by default. If we want to avoid having problems with the dropdown, don't you think we can keep it required and setting 'en' selected by default?

**Comment by nrobert** [comment]
I quickly checked after the deployment, it is resolved now 👍
