### ISSUE TITLE
Support API image limitations by checking request image

### ISSUE THREAD

**Issue by nrobert** [PeterOrneholm/cognitive-workbench#8]
Computer Vision, Face and Custom Vision have different restrictions for:

- image type
- image size in bytes
- image size in pixels

Currently, the site is directly using those APIs by providing the URL: nothing is checked, and the API will throw an error if the image is not valid.

Improvement possibilities (sort by complexity of implementation, easier first):

1. Handle the error thrown by the API and display this error to the user (note: the API call is count as billable in that case)
2. Check the restrictions by loading the image and throw an error instead of calling the API if the image is not valid, so that the user can fix the error (and there will be no API call, so nothing billable for the user)
3. Check the restrictions by loading the image and downscale the image if it is too large (in terms of pixels or size), so that the call will be possible

**Comment by PeterOrneholm** [comment]
Good suggestions. We could (and should) handle errors better in general.

Regarding errors. In other scenarios, you should not (for security reasons) expose the raw exception details to the end user, but I'd say that's exactly what we should do here, as all data are your own and the purpose of the site is to understand what's happening.

**Comment by nrobert** [comment]
To be more clear about what I have in mind: the idea would be to display only underlaying API exceptions (4xx result codes) which contains information for the user explaining why his/her query failed. For other things yes, a generic error management instead of the 500 on the global page would be great.
